name: Docker Image CI

on:
  push:
    branches: [ main ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn clean install
    - name : Docker Login
      run :  docker login -u chitra2020 -p comedy8855
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag chitra2020/timesheetapp:latest
    - name : Docker Push
      run : docker push chitra2020/timesheetapp:latest
